host = "0.0.0.0"
port = 7999
workers = 1
concurrent_limit = 65535
timeout = 600
connect_timeout = 60
tcp_keepalive = 60
tb_enable = false
tb_store_strategy = "mem"
tb_redis_url = ["redis://127.0.0.1:6379"]
tb_capacity = 60
tb_fill_rate = 1
tb_expired = 86400
disable_webui = false
